# mkdocs.yml

site_name: Guia de Acessibilidade
site_url: https://github.com/UnBIHC2025-1/IHC-2025.1-Grupo06
repo_url: https://github.com/UnBIHC2025-1/IHC-2025.1-Grupo06
repo_name: 2025.1 - IHC - Grupo 6
use_directory_urls: False

nav:
  - Início: index.md

  - Desenvolvimento Web:
    - Conteúdo Não Textual: devWeb/devWeb.md

  - Design:
    - Design: design/design.md

  - Geração de Conteúdo:
    - Conteúdo: geracaoConteudo/conteudo.md

  - Gestão de Projetos:
    - Gestão de Projetos: gestaoProjeto/gestaoProjeto.md

  - Ferramentas:
    - Ferramentas de Acessibilidade: tools/ferramentas.md

theme:
  name: material
  logo: imagens/logo-verificaaa.png
  favicon: imagens/logo-verificaaa.png

  font:
    text: Poppins

  icon:
    repo: fontawesome/brands/github

  palette:
    - scheme: light
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Alternar para modo escuro
    - scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Alternar para modo claro

  nav_style: dark
  language: pt
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - navigation.path
    - navigation.prune
    - content.code.copy
    - toc.integrate
    - search.suggest
    - search.highlight
    - navigations.indexes

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.inlinehilite
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.snippets
  - pymdownx.magiclink

extra_css:
  - stylesheets/extra.css
